[workspace]
members = [
    "crates/memory-engine-beta-app",
    "crates/memory-engine-core",
    "crates/memory-engine-generation",
    "crates/memory-engine-service",
    "crates/memory-engine-persistence",
    "crates/memory-engine-study",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.0.0"

[workspace.lints.clippy]
all = "deny"
pedantic = "warn"
